name: 'incremental_deriv'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  incremental_deriv:
    staging:
      +materialized: incremental
      +schema: staging
    intermediate:
      +materialized: incremental
      +schema: intermediate 